# ansible-playbook -i ~/ansible-hosts push_config.yml -v
---
- name: Configure nodes from templates
  hosts: arista5
  vars:
    eapi_conn:
      host: '{{ ansible_host }}'
      username: "{{ username }}"
      password: "{{ password }}"
      #transport: ssh
      use_ssl: true
      validate_certs: false
    ports:
      - { name: Ethernet2, descr: Configured by ansible, vlan: 100 }
      - { name: Ethernet3, descr: host32-eth0 }


  tasks:
    - name: Ensure backups dir exists
      file:
        path: backups
        state: directory

    - name: Ensure config dir exists
      file:
        path: configs
        state: directory

    - name: Render config sections from templates
      template:
        src: templates/{{ ansible_host }}-adv.j2
        dest: configs/{{ ansible_host }}-new.cfg

#    - name: Push config commands to nodes with built-in
#      eos_config:
#        provider: "{{ eapi_conn }}"
#        src: configs/{{ ansible_host }}-new.cfg
 
    - name: Push config commands to nodes with napalm
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: eos
        config_file: "configs/{{ ansible_host }}-new.cfg"
        archive_file: "backups/{{ ansible_host }}-old.cfg"
        commit_changes: True
        replace_config: False
        diff_file: "{{ ansible_host }}.diff"

#    - name: Push config commands to nodes with networktocode
#      ntc_config_command:
#        platform: "{{ ntc_platform }}"
#        host: "{{ ansible_host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
#        commands_file: configs/{{ ansible_host }}-new.cfg
